[cache]
dir = "/tmp/gs++/cache"

[grpc]
host = "0.0.0.0"
port = 50051

[bitcoind]
host = "${BITCOIND_ADDR}"
port = 18443
user = "bitcoin"
pass = "password"
zmq_port = 28332

[bchd]
host = "${BCHD_ADDR}"
port = 18335
cert_path = "${BCHD_CERT_PATH}"

[utxo]
checkpoint = "./utxo-checkpoints/QmXkBQJrMKkCKNbwv4m5xtnqwU9Sq7kucPigvZW8mWxcrv"
block_height = 543375
block_hash = "0000000000000000000000000000000000000000000000000000000000000000"
checkpoint_load = false
checkpoint_save = false

[zmqpub]
bind = "tcp://0.0.0.0:29069"

[graphsearch]
max_exclusion_set_size = 5
private_key = "0000000000000000000000000000000000000000000000000000000000000000"

[services]
graphsearch = true
graphsearch_rpc = true
zmq = true
grpc = true
utxosync = false
cache = true
zmqpub = true
