[cache]
dir = "/tmp/gs++/cache"

[grpc]
host = "0.0.0.0"
port = 50051

[bitcoind]
host = "0.0.0.0"
port = 8332
user = "user"
pass = "password"
zmq_port = 28332

[utxo]
checkpoint = "./utxo-checkpoints/QmXkBQJrMKkCKNbwv4m5xtnqwU9Sq7kucPigvZW8mWxcrv"
block_height = 543375
block_hash = "0000000000000000000000000000000000000000000000000000000000000000"
checkpoint_load = false
checkpoint_save = false

[zmqpub]
bind = "tcp://127.0.0.1:29069"

[services]
graphsearch = true
graphsearch_rpc = true
zmq = true
grpc = true
utxosync = false
cache = true
zmqpub = true
